### ISSUE TITLE
Request sent by email

### ISSUE THREAD

**Issue by youthHan** [ShareChatAI/3MASSIV#1]
Hi, thank you for your work releasing the dataset. I have sent the request and the signed agreement via email for over a week and no replies have been received. Can you please have a check and indicate a possible timeline of the approval？Thanks in advance.

**Comment by ShareChatAI** [comment]
Hi @youthHan,

Thanks for your interest in our work. 

As discussed on email, we have shared the access to the dataset. 

Feel free to reopen this issue in case of further queries.
